name: Build and Publish Images

on:
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-api:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1.6.0

      - name: Login to DockerHub
        uses: docker/login-action@v1.14.1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build image
        uses: docker/build-push-action@v2.10.0
        with:
          context: ./backend/
          tags: saitohbp/aws.simple.example.backend:latest
          push: true
          
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
